// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import routeProps from './routeProps';

if (process.env.NODE_ENV === 'development') {
  Object.entries(routeProps).forEach(([key, value]) => {
    const internalProps = ['path', 'id', 'parentId', 'isLayout', 'isWrapper', 'layout', 'clientLoader'];
    Object.keys(value).forEach((prop) => {
      if (internalProps.includes(prop)) {
        throw new Error(
          `[UmiJS] route '${key}' should not have '${prop}' prop, please remove this property in 'routeProps'.`
        )
      }
    })
  })
}

import React from 'react';

export async function getRoutes() {
  const routes = {"Table/components/CreateForm":{"path":"Table/components/CreateForm","id":"Table/components/CreateForm"},"Table/components/UpdateForm":{"path":"Table/components/UpdateForm","id":"Table/components/UpdateForm"},"Access/index":{"path":"Access","id":"Access/index"},"Table/index":{"path":"Table","id":"Table/index"},"Home/index":{"path":"Home","id":"Home/index"}} as const;
  return {
    routes,
    routeComponents: {
'Table/components/CreateForm': React.lazy(() => import(/* webpackChunkName: "src__pages__Table__components__CreateForm" */'../../../src/pages/Table/components/CreateForm.tsx')),
'Table/components/UpdateForm': React.lazy(() => import(/* webpackChunkName: "src__pages__Table__components__UpdateForm" */'../../../src/pages/Table/components/UpdateForm.tsx')),
'Access/index': React.lazy(() => import(/* webpackChunkName: "src__pages__Access__index" */'../../../src/pages/Access/index.tsx')),
'Table/index': React.lazy(() => import(/* webpackChunkName: "src__pages__Table__index" */'../../../src/pages/Table/index.tsx')),
'Home/index': React.lazy(() => import(/* webpackChunkName: "src__pages__Home__index" */'../../../src/pages/Home/index.tsx')),
},
  };
}
